import { ArrowDown, ArrowRight, ArrowUp, Clock3, MessageSquareText } from "lucide-react";
import type { PatientResponse, TrendSignal } from "@/lib/api";

const NAME: Record<string, string> = { systolic_bp: "Systolic BP", diastolic_bp: "Diastolic BP", heart_rate: "Heart rate", spo2: "SpO₂", respiratory_rate: "Respiratory rate", temperature: "Temperature" };
const UNIT: Record<string, string> = { systolic_bp: "mmHg", diastolic_bp: "mmHg", heart_rate: "bpm", spo2: "%", respiratory_rate: "/min", temperature: "°C" };

export function WhyNow({ data, compact = false }: { data: PatientResponse; compact?: boolean }) {
  const signals = data.trends.signals.filter((signal) => signal.concerning && signal.current !== null).slice(0, 3);
  const speech = data.events.filter((event) => event.source === "speech" && event.quote.trim()).at(-1);
  const priority = data.priority;
  return <section className={`why-now relative overflow-hidden bg-[#163b34] text-white ${compact ? "p-5" : "p-6"}`}>
    <div className="echo-trace absolute inset-x-0 top-0 h-px" />
    <div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.18em] text-[#8fc5b6]">Why now?</p><h3 className={`${compact ? "mt-1 text-[18px]" : "mt-2 text-[24px]"} font-medium tracking-tight`}>{signals.length ? `${signals.length} signal${signals.length === 1 ? "" : "s"} now ${signals.length === 1 ? "supports" : "agree on"} concern` : "No sustained deterioration"}</h3></div>{priority && <div className="text-right"><p className="text-[9px] uppercase tracking-wide text-white/45">Ward priority</p><p className="mt-0.5 text-[24px] font-semibold tabular">#{priority.rank}</p></div>}</div>
    <div className="mt-5 divide-y divide-white/10 border-y border-white/10">{signals.map((signal) => <SignalChange key={signal.observation} signal={signal} />)}</div>
    {speech && <div className="mt-4 flex gap-3"><MessageSquareText size={15} className="mt-0.5 shrink-0 text-[#8fc5b6]" /><div><p className="text-[11px] leading-relaxed text-white/85">“{speech.quote}”</p><p className="mt-1 text-[8px] font-semibold uppercase tracking-[.14em] text-white/35">{speech.speaker} · evidence {speech.id}</p></div></div>}
    <div className="mt-5 flex items-center gap-3"><div className="h-px flex-1 bg-gradient-to-r from-[#70ad9d] to-white/20" /><ArrowRight size={14} className="text-[#8fc5b6]" /><span className="text-[10px] font-semibold uppercase tracking-[.14em]">{priority?.level.replace(/_/g, " ") ?? "Stable"}</span></div>
  </section>;
}

export function WhatChanged({ data }: { data: PatientResponse }) {
  const changes = data.trends.signals.filter((signal) => signal.concerning).slice(0, 2);
  const gap = data.care.gaps[0];
  const items = [...changes.map((signal) => ({ kind: "Worsened", title: NAME[signal.observation] ?? signal.observation, detail: `${signal.baseline ?? "—"} → ${signal.current ?? "—"} ${UNIT[signal.observation] ?? ""}` })), ...(gap ? [{ kind: "Delayed", title: "Reassessment", detail: `${Math.max(1, Math.round(gap.overdueMs / 60000))} min overdue` }] : [])].slice(0, 3);
  return <section className="border-y border-line bg-white px-5 py-5"><div className="flex items-end justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[var(--accent)]">What changed since last round?</p><h3 className="mt-1 text-[18px] font-medium">{items.length} meaningful change{items.length === 1 ? "" : "s"}</h3></div><p className="text-[9px] text-faint">Everything else remains stable</p></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{items.length ? items.map((item, index) => <div key={`${item.title}-${index}`} className="group border-l border-[#9eb7ae] pl-3 transition hover:border-[var(--accent)]"><div className="flex items-center gap-2"><span className="text-[9px] font-semibold tabular text-faint">0{index + 1}</span><span className="text-[8px] font-bold uppercase tracking-[.14em] text-[var(--lvl-high)]">{item.kind}</span></div><p className="mt-2 text-[12px] font-semibold">{item.title}</p><p className="mt-1 text-[11px] tabular text-dim">{item.detail}</p></div>) : <p className="text-[11px] text-dim">No meaningful change detected.</p>}</div></section>;
}

export function CareGapVisual({ data }: { data: PatientResponse }) { const gap = data.care.gaps[0]; if (!gap) return null; return <section className="bg-[#fbfaf7] p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[var(--lvl-watch)]">Care gap</p><p className="mt-1 text-[14px] font-semibold">Patient condition moved faster than workflow</p></div><Clock3 size={18} className="text-[var(--lvl-watch)]" /></div><div className="mt-5 grid grid-cols-[100px_1fr] gap-x-4 gap-y-3 text-[9px] uppercase tracking-wide text-faint"><span>Patient state</span><div className="relative h-5 border-b border-[var(--lvl-high)]"><span className="absolute right-[12%] bottom-0 h-4 w-px bg-[var(--lvl-high)]" /><span className="absolute right-[9%] -top-1 text-[var(--lvl-high)]">HIGH</span></div><span>Care response</span><div className="relative h-5 border-b border-dashed border-[var(--lvl-watch)]"><span className="absolute left-[58%] bottom-[-4px] h-2 w-2 rounded-full bg-[var(--lvl-watch)]" /><span className="absolute left-[52%] -top-1 text-[var(--lvl-watch)]">WAITING</span></div></div><div className="mt-4 flex items-start gap-2 border-t border-line pt-3"><ArrowUp size={13} className="mt-0.5 text-[var(--lvl-watch)]" /><p className="text-[10px] leading-relaxed text-dim">{gap.summary} · {Math.max(1, Math.round(gap.overdueMs / 60000))} minutes beyond expected response.</p></div></section>; }

function SignalChange({ signal }: { signal: TrendSignal }) { const down = signal.current !== null && signal.baseline !== null && signal.current < signal.baseline; return <div className="grid grid-cols-[1fr_auto_auto] items-center gap-4 py-2.5"><span className="text-[10px] font-medium text-white/65">{NAME[signal.observation] ?? signal.observation}</span><span className="text-[13px] font-semibold tabular">{signal.baseline ?? "—"} <ArrowRight className="mx-1 inline text-white/30" size={11} /> {signal.current ?? "—"}</span><span className="flex h-6 w-6 items-center justify-center rounded-full bg-white/10 text-[#efb2a8]">{down ? <ArrowDown size={12} /> : <ArrowUp size={12} />}</span></div>; }
